insert into category (description) values ('American');
insert into category (description) values ('Italian');
insert into category (description) values ('Mexican');
insert into category (description) values ('Fast Food');
insert into unit_of_measure (description) values ('Each');
insert into unit_of_measure (description) values ('Dash');
insert into unit_of_measure (description) values ('Teaspoon');
insert into unit_of_measure (description) values ('Tablespoon');
insert into unit_of_measure (description) values ('Cup');
insert into unit_of_measure (description) values ('Pint');
insert into unit_of_measure (description) values ('Ounce');
