INSERT INTO Category (Description) VALUES ('American');
INSERT INTO Category (Description) VALUES ('Italian');
INSERT INTO Category (Description) VALUES ('Mexican');
INSERT INTO Category (Description) VALUES ('Fast Food');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Teaspoon');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Tablespoon');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Cup');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Pinch');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Ounce');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Dash');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Clove');
INSERT INTO Unit_Of_Measure (Description) VALUES ('Pint');